# Generated by Django 6.0.6 on 2026-06-18 01:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100, unique=True, verbose_name='Endereço')),
                ('predio', models.CharField(blank=True, max_length=10, null=True, verbose_name='Prédio')),
                ('posicao', models.CharField(blank=True, max_length=20, null=True, verbose_name='Posição')),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100, unique=True, verbose_name='Código do Produto')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('palletizacao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Paletização')),
                ('valor_palete', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor Palete')),
                ('pac', models.CharField(blank=True, max_length=100, null=True, verbose_name='PAC')),
                ('material', models.CharField(blank=True, max_length=100, null=True, verbose_name='Material')),
                ('texto_breve_material', models.CharField(blank=True, max_length=255, null=True, verbose_name='Texto Breve Material')),
                ('sku_senior', models.CharField(blank=True, max_length=100, null=True, verbose_name='SKU Senior')),
                ('endereco_senior', models.CharField(blank=True, max_length=100, null=True, verbose_name='Endereço Senior')),
                ('qtd_senior', models.IntegerField(blank=True, null=True, verbose_name='Quantidade Senior')),
                ('tipo_pallet', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de Pallet')),
                ('tipo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.CreateModel(
            name='Rua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código da Rua')),
                ('modelo_planilha', models.CharField(blank=True, max_length=50, null=True, verbose_name='Modelo da Planilha')),
            ],
            options={
                'verbose_name': 'Rua',
                'verbose_name_plural': 'Ruas',
            },
        ),
        migrations.CreateModel(
            name='Contagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_produto', models.CharField(max_length=100, verbose_name='Código do Produto')),
                ('descricao_produto', models.CharField(max_length=255, verbose_name='Descrição')),
                ('pallets', models.IntegerField(verbose_name='Quantidade de Pallets')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('data_hora', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora da Contagem')),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Operador')),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contagens', to='core.endereco', verbose_name='Endereço')),
            ],
            options={
                'verbose_name': 'Contagem',
                'verbose_name_plural': 'Contagens',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='PerfilOperador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL, verbose_name='Utilizador')),
                ('ruas_permitidas', models.ManyToManyField(blank=True, to='core.rua', verbose_name='Ruas Autorizadas')),
            ],
            options={
                'verbose_name': 'Perfil de Operador',
                'verbose_name_plural': 'Perfis de Operadores',
            },
        ),
        migrations.AddField(
            model_name='endereco',
            name='rua',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enderecos', to='core.rua', verbose_name='Rua'),
        ),
        migrations.CreateModel(
            name='PosicaoSenior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_senior', models.CharField(max_length=100, verbose_name='SKU Senior')),
                ('qtd_senior', models.IntegerField(default=0, verbose_name='Quantidade Senior')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posicoes_senior', to='core.endereco', verbose_name='Endereço')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posicoes_senior', to='core.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Posição Senior',
                'verbose_name_plural': 'Posições Senior',
                'unique_together': {('endereco', 'produto')},
            },
        ),
    ]
