# Generated by Django 6.0.6 on 2026-06-18 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='endereco',
            options={'ordering': ['codigo'], 'verbose_name': 'Endereço', 'verbose_name_plural': 'Endereços'},
        ),
        migrations.AlterModelOptions(
            name='posicaosenior',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='posicaosenior',
            unique_together=set(),
        ),
    ]
