# Generated by Django 6.0.6 on 2026-06-18 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_endereco_options_alter_posicaosenior_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posicaosenior',
            options={'ordering': ['endereco__codigo'], 'verbose_name': 'Posição Senior', 'verbose_name_plural': 'Posições Senior'},
        ),
        migrations.AddField(
            model_name='contagem',
            name='historico_edicoes',
            field=models.TextField(blank=True, null=True, verbose_name='Histórico de Edições'),
        ),
        migrations.AlterUniqueTogether(
            name='posicaosenior',
            unique_together={('endereco', 'produto')},
        ),
    ]
