# Generated by Django 6.0.6 on 2026-06-19 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_posicaosenior_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='andar_num',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Andar (Nº)'),
        ),
        migrations.AddField(
            model_name='endereco',
            name='posicao_num',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Posição (Nº)'),
        ),
        migrations.AddField(
            model_name='endereco',
            name='predio_num',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Prédio (Nº)'),
        ),
        migrations.AddField(
            model_name='endereco',
            name='rua_num',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Rua (Nº Ordenação)'),
        ),
    ]
