# Generated by Django 6.0.6 on 2026-06-19 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_endereco_andar_num_endereco_posicao_num_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endereco',
            name='posicao',
        ),
        migrations.RemoveField(
            model_name='endereco',
            name='predio',
        ),
        migrations.AlterField(
            model_name='endereco',
            name='andar_num',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Andar'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='posicao_num',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Posição'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='predio_num',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Prédio'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='rua_num',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Rua'),
        ),
    ]
