# Generated by Django 6.0.6 on 2026-06-19 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_endereco_posicao_remove_endereco_predio_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='endereco',
            options={'ordering': ['rua_num', 'predio_num', 'andar_num', 'posicao_num'], 'verbose_name': 'Endereço', 'verbose_name_plural': 'Endereços'},
        ),
        migrations.AlterModelOptions(
            name='rua',
            options={'ordering': ['ordem'], 'verbose_name': 'Rua', 'verbose_name_plural': 'Ruas'},
        ),
        migrations.AddField(
            model_name='rua',
            name='ordem',
            field=models.IntegerField(default=0, verbose_name='Ordem de Exibição'),
        ),
    ]
