# Generated by Django 6.0.6 on 2026-06-19 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_endereco_options_alter_rua_options_rua_ordem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posicaosenior',
            options={'ordering': ['endereco__rua_num', 'endereco__predio_num', 'endereco__andar_num', 'endereco__posicao_num'], 'verbose_name': 'Posição Senior', 'verbose_name_plural': 'Posições Senior'},
        ),
    ]
