# Generated by Django 6.0.6 on 2026-06-19 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_posicaosenior_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='contagem',
            name='em_conflito',
            field=models.BooleanField(default=False, help_text='Indica se dois operadores contaram o mesmo endereço offline', verbose_name='Em Conflito'),
        ),
        migrations.AddField(
            model_name='contagem',
            name='uuid_aparelho',
            field=models.CharField(blank=True, help_text='ID único do celular/coletor que fez a contagem', max_length=100, null=True, verbose_name='UUID do Aparelho'),
        ),
    ]
