# Generated by Django 6.0.6 on 2026-06-20 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_contagem_atualizado_por'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contagem',
            name='e_recontagem',
            field=models.BooleanField(default=False, verbose_name='É Recontagem'),
        ),
        migrations.CreateModel(
            name='TarefaRecontagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('concluido_em', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDO', 'Concluído')], default='PENDENTE', max_length=20)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas_recontagem', to='core.endereco')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas_recontagem', to='core.produto')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas_recontagem', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tarefa de Recontagem',
                'verbose_name_plural': 'Tarefas de Recontagem',
                'ordering': ['status', '-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='contagem',
            name='tarefa_recontagem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contagens_recontagem', to='core.tarefarecontagem', verbose_name='Tarefa de Recontagem'),
        ),
    ]
