# Generated by Django 6.0.6 on 2026-06-20 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_contagem_e_recontagem_tarefarecontagem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contagem',
            name='foi_descartada',
            field=models.BooleanField(default=False, help_text='Marcado como True se a contagem perdeu um conflito e foi arquivada pelo gestor.', verbose_name='Foi Descartada?'),
        ),
    ]
