# Generated by Django 6.0.6 on 2026-06-20 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_contagem_foi_descartada'),
    ]

    operations = [
        migrations.AddField(
            model_name='contagem',
            name='id_local',
            field=models.CharField(blank=True, db_index=True, help_text='Evita duplicatas se a internet cair durante a sincronização.', max_length=100, null=True, verbose_name='ID Local (Idempotência)'),
        ),
    ]
