# Generated by Django 6.0.6 on 2026-06-20 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_contagem_id_local'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfiloperador',
            name='cargo',
            field=models.CharField(choices=[('OPERADOR', 'Operador (Apenas App)'), ('LIDER', 'Líder de Rua (App + Painel Básico)'), ('GESTOR', 'Gestor de Estoque (Acesso Total)')], default='OPERADOR', max_length=20, verbose_name='Nível de Acesso'),
        ),
    ]
