# Generated by Django 6.0.6 on 2026-06-20 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_perfiloperador_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='contagem',
            name='numero_contagem',
            field=models.IntegerField(default=1, help_text='Ex: 1 para primeira contagem, 2 para recontagem.', verbose_name='Número da Contagem'),
        ),
    ]
