# Generated by Django 6.0.6 on 2026-06-20 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_contagem_numero_contagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='endereco_senior',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='qtd_senior',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='sku_senior',
        ),
        migrations.DeleteModel(
            name='PosicaoSenior',
        ),
    ]
