# Generated by Django 6.0.6 on 2026-06-21 00:46

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_endereco_ativo_produto_ativo_rua_ativo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalContagem',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('codigo_produto', models.CharField(max_length=100, verbose_name='Código do Produto')),
                ('descricao_produto', models.CharField(max_length=255, verbose_name='Descrição')),
                ('pallets', models.IntegerField(verbose_name='Quantidade de Pallets')),
                ('numero_contagem', models.IntegerField(default=1, help_text='Ex: 1 para primeira contagem, 2 para recontagem.', verbose_name='Número da Contagem')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('historico_edicoes', models.TextField(blank=True, null=True, verbose_name='Histórico de Edições')),
                ('data_hora', models.DateTimeField(blank=True, editable=False, verbose_name='Data/Hora da Contagem')),
                ('uuid_aparelho', models.CharField(blank=True, help_text='ID único do celular/coletor que fez a contagem', max_length=100, null=True, verbose_name='UUID do Aparelho')),
                ('id_local', models.CharField(blank=True, db_index=True, help_text='Evita duplicatas se a internet cair durante a sincronização.', max_length=100, null=True, verbose_name='ID Local (Idempotência)')),
                ('em_conflito', models.BooleanField(default=False, help_text='Indica se dois operadores contaram o mesmo endereço offline', verbose_name='Em Conflito')),
                ('foi_descartada', models.BooleanField(default=False, help_text='Marcado como True se a contagem perdeu um conflito e foi arquivada pelo gestor.', verbose_name='Foi Descartada?')),
                ('e_recontagem', models.BooleanField(default=False, verbose_name='É Recontagem')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('atualizado_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Última edição por')),
                ('endereco', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.endereco', verbose_name='Endereço')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('operador', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Operador')),
                ('tarefa_recontagem', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.tarefarecontagem', verbose_name='Tarefa de Recontagem')),
            ],
            options={
                'verbose_name': 'historical Contagem',
                'verbose_name_plural': 'historical Contagens',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalProduto',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=100, verbose_name='Código do Produto')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('palletizacao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Paletização')),
                ('valor_palete', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor Palete')),
                ('pac', models.CharField(blank=True, max_length=100, null=True, verbose_name='PAC')),
                ('material', models.CharField(blank=True, max_length=100, null=True, verbose_name='Material')),
                ('texto_breve_material', models.CharField(blank=True, max_length=255, null=True, verbose_name='Texto Breve Material')),
                ('tipo_pallet', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de Pallet')),
                ('tipo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Produto',
                'verbose_name_plural': 'historical Produtos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
