# Generated by Django 6.0.6 on 2026-06-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_historicalcontagem_historicalproduto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versao_minima_app', models.CharField(default='1.0.0', max_length=20, verbose_name='Versão mínima do App')),
            ],
            options={
                'verbose_name': 'Configuração do Sistema',
                'verbose_name_plural': 'Configurações do Sistema',
            },
        ),
        migrations.AddField(
            model_name='perfiloperador',
            name='push_token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Push Token (Expo)'),
        ),
    ]
