# Generated by Django 6.0.6 on 2026-06-21 16:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_configuracaosistema_perfiloperador_push_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contagem',
            name='data_contagem',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Data da contagem'),
        ),
        migrations.AddField(
            model_name='historicalcontagem',
            name='data_contagem',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Data da contagem'),
        ),
        migrations.AddConstraint(
            model_name='contagem',
            constraint=models.UniqueConstraint(fields=('operador', 'endereco', 'codigo_produto', 'data_contagem'), name='unico_operador_endereco_produto_por_dia'),
        ),
    ]
