# Generated by Django 6.0.6 on 2026-06-21 16:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_contagem_data_contagem_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='contagem',
            index=models.Index(fields=['data_contagem', 'endereco', 'codigo_produto'], name='core_contag_data_co_8a5981_idx'),
        ),
        migrations.AddIndex(
            model_name='contagem',
            index=models.Index(fields=['operador', 'data_contagem'], name='core_contag_operado_6643fd_idx'),
        ),
        migrations.AddIndex(
            model_name='contagem',
            index=models.Index(fields=['-data_hora'], name='core_contag_data_ho_d82a06_idx'),
        ),
    ]
