# Generated by Django 6.0.6 on 2026-06-22 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_contagem_core_contag_data_co_8a5981_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloPlanilha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Modelo')),
            ],
            options={
                'verbose_name': 'Modelo de Planilha',
                'verbose_name_plural': 'Modelos de Planilha',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='endereco',
            name='contagem_realizada',
            field=models.BooleanField(default=False, verbose_name='Já foi contado?'),
        ),
        migrations.AddField(
            model_name='endereco',
            name='ultima_contagem_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última contagem registrada'),
        ),
        migrations.AddField(
            model_name='tarefarecontagem',
            name='criticidade',
            field=models.CharField(choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Média'), ('ALTA', 'Alta')], default='BAIXA', max_length=10, verbose_name='Criticidade'),
        ),
        migrations.AlterField(
            model_name='rua',
            name='modelo_planilha',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.modeloplanilha', verbose_name='Modelo da Planilha'),
        ),
    ]
