# Generated by Django 6.0.6 on 2026-06-24 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_modeloplanilha_endereco_contagem_realizada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contagem',
            name='codigo_produto',
            field=models.CharField(help_text='Código do produto com até 6 dígitos', max_length=6, verbose_name='Código do Produto'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='codigo',
            field=models.CharField(help_text='Código do endereço com até 6 caracteres (ex: A1203 ou 12B045)', max_length=6, unique=True, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='rua_num',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Número da rua'),
        ),
        migrations.AlterField(
            model_name='historicalcontagem',
            name='codigo_produto',
            field=models.CharField(help_text='Código do produto com até 6 dígitos', max_length=6, verbose_name='Código do Produto'),
        ),
        migrations.AlterField(
            model_name='historicalproduto',
            name='codigo',
            field=models.CharField(db_index=True, help_text='Código com exatamente 6 dígitos (ex.: 123456)', max_length=6, verbose_name='Código do Produto'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='codigo',
            field=models.CharField(help_text='Código com exatamente 6 dígitos (ex.: 123456)', max_length=6, unique=True, verbose_name='Código do Produto'),
        ),
    ]
