# Generated by Django 6.0.6 on 2026-06-27 04:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_contagem_codigo_produto_alter_endereco_codigo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_produto', models.CharField(max_length=6, verbose_name='Código do Produto')),
                ('descricao_produto', models.CharField(max_length=255, verbose_name='Descrição')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantidade')),
                ('tipo_unidade', models.CharField(choices=[('pallet', 'Pallet'), ('pack', 'Pack'), ('unidade', 'Unidade')], max_length=10, verbose_name='Tipo de Unidade')),
                ('observacao', models.TextField(blank=True, null=True)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='historicalproduto',
            name='packs_por_pallet',
            field=models.IntegerField(blank=True, help_text='Ex: 48', null=True, verbose_name='Packs por Pallet'),
        ),
        migrations.AddField(
            model_name='historicalproduto',
            name='unidades_por_pack',
            field=models.IntegerField(blank=True, help_text='Ex: 24', null=True, verbose_name='Unidades por Pack'),
        ),
        migrations.AddField(
            model_name='produto',
            name='packs_por_pallet',
            field=models.IntegerField(blank=True, help_text='Ex: 48', null=True, verbose_name='Packs por Pallet'),
        ),
        migrations.AddField(
            model_name='produto',
            name='unidades_por_pack',
            field=models.IntegerField(blank=True, help_text='Ex: 24', null=True, verbose_name='Unidades por Pack'),
        ),
        migrations.AlterField(
            model_name='historicalproduto',
            name='codigo',
            field=models.CharField(help_text='Código com exatamente 6 dígitos (ex.: 123456)', max_length=6, verbose_name='Código do Produto'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='codigo',
            field=models.CharField(help_text='Código com exatamente 6 dígitos (ex.: 123456)', max_length=6, verbose_name='Código do Produto'),
        ),
        migrations.AddConstraint(
            model_name='produto',
            constraint=models.UniqueConstraint(condition=models.Q(('ativo', True)), fields=('codigo',), name='unique_codigo_produto_ativo'),
        ),
        migrations.AddField(
            model_name='avaria',
            name='operador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Operador'),
        ),
        migrations.AddField(
            model_name='avaria',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.produto', verbose_name='Produto'),
        ),
    ]
