# Generated by Django 6.0.6 on 2026-06-27 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_avaria_historicalproduto_packs_por_pallet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfiloperador',
            name='current_session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
