# Generated by Django 6.0.6 on 2026-06-28 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_perfiloperador_current_session_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContagemSessao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
                ('inicio', models.DateTimeField(blank=True, null=True)),
                ('fim', models.DateTimeField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('PRIMEIRA', '1ª Contagem'), ('SEGUNDA', '2ª Contagem'), ('TERCEIRA', '3ª Contagem (Definitiva)'), ('AVARIA', 'Avaria')], default='PRIMEIRA', max_length=20)),
                ('contagem_informada', models.BooleanField(default=False)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('ruas', models.ManyToManyField(blank=True, to='core.rua')),
                ('sessao_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.contagemsessao')),
                ('sessao_validada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validada_por', to='core.contagemsessao')),
            ],
        ),
        migrations.AddField(
            model_name='contagem',
            name='sessao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.contagemsessao', verbose_name='Sessão'),
        ),
        migrations.AddField(
            model_name='historicalcontagem',
            name='sessao',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.contagemsessao', verbose_name='Sessão'),
        ),
    ]
